'use client';

/**
 * MapSearch — "Hanapin ang lugar": type a landmark, barangay or town, jump to it.
 *
 * A dispatcher on the phone hears "sa tabi ng Naval Central School" or "sa
 * Barangay Larrazabal" and has to find it NOW, not pan around an island
 * looking for a label. This searches every named landmark and place in the
 * self-hosted Biliran extract (public/map/places.json, generated by
 * scripts/make-map-assets.mjs — the same data the map draws), flies there, and
 * drops a pulsing ring on the spot.
 *
 * Fully offline from third parties: no geocoding service is called.
 */

import { useEffect, useMemo, useRef, useState } from 'react';
import type { Map as MlMap, Marker } from 'maplibre-gl';
import { Building2, Flame, Hospital, Landmark, MapPin, Search, Shield, Ship, Stethoscope, X } from 'lucide-react';
import { cn } from '@/lib/utils';

interface Place {
  /** Name. */
  n: string;
  /** OpenMapTiles class: hospital, school, village, town … */
  c: string;
  /** 'poi' (a landmark) or 'place' (a town, barangay, sitio). */
  k: 'poi' | 'place';
  lat: number;
  lng: number;
}

const KIND_LABEL: Record<string, string> = {
  hospital: 'Hospital', doctors: 'Health centre', police: 'Police station', fire_station: 'Fire station',
  town_hall: 'Municipal / barangay hall', ferry_terminal: 'Port', school: 'School', college: 'College',
  place_of_worship: 'Church', town: 'Town', city: 'City', village: 'Barangay', hamlet: 'Sitio',
  suburb: 'Barangay', neighbourhood: 'Purok', island: 'Island', office: 'Office', fuel: 'Gas station',
  pharmacy: 'Pharmacy', bank: 'Bank', lodging: 'Lodging', shop: 'Store', grocery: 'Store',
};
const KIND_ICON: Record<string, typeof MapPin> = {
  hospital: Hospital, doctors: Stethoscope, police: Shield, fire_station: Flame,
  town_hall: Landmark, ferry_terminal: Ship, office: Building2,
};
/** Ranked first when names tie: what a dispatcher most often searches for. */
const PRIORITY: Record<string, number> = {
  hospital: 0, doctors: 0, police: 0, fire_station: 0, town_hall: 1, town: 1, city: 1, ferry_terminal: 2,
  village: 2, suburb: 2, school: 3, college: 3, place_of_worship: 3, hamlet: 4,
};

const fold = (s: string) => s.normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase();

function matchRank(name: string, q: string): number {
  if (name === q) return 0;
  if (name.startsWith(q)) return 1;
  if (name.split(/[\s,.-]+/).some(w => w.startsWith(q))) return 2;
  return 3;
}

let placesPromise: Promise<Place[]> | null = null;
function loadPlaces(): Promise<Place[]> {
  placesPromise ??= fetch('/map/places.json').then(r => (r.ok ? r.json() : [])).catch(() => []);
  return placesPromise;
}

export function MapSearch({ map, maplibre, className }: {
  map: MlMap | null;
  maplibre: typeof import('maplibre-gl') | null;
  className?: string;
}) {
  const [places, setPlaces] = useState<Place[] | null>(null);
  const [query, setQuery] = useState('');
  const [open, setOpen] = useState(false);
  const [active, setActive] = useState(0);
  const [picked, setPicked] = useState<Place | null>(null);
  const ringRef = useRef<Marker | null>(null);
  const boxRef = useRef<HTMLDivElement>(null);

  // Loaded on first focus, not on page load: most shifts never search.
  function ensureLoaded() {
    if (!places) void loadPlaces().then(setPlaces);
  }

  const results = useMemo(() => {
    const q = fold(query.trim());
    if (!q || !places) return [];
    const words = q.split(/\s+/);
    return places
      .map(p => ({ p, name: fold(p.n) }))
      .filter(({ name }) => words.every(w => name.includes(w)))
      // Exact name first, then names that start with the query, then names
      // with a word that does, then the rest; ties go to what a dispatcher
      // most often looks for (hospitals, stations, towns), then A-Z.
      .sort((a, b) =>
        matchRank(a.name, q) - matchRank(b.name, q)
        || (PRIORITY[a.p.c] ?? 5) - (PRIORITY[b.p.c] ?? 5)
        || a.p.n.localeCompare(b.p.n))
      .slice(0, 8)
      .map(r => r.p);
  }, [query, places]);

  useEffect(() => { setActive(0); }, [query]);

  // Close the list on an outside click.
  useEffect(() => {
    const onDown = (e: PointerEvent) => {
      if (boxRef.current && !boxRef.current.contains(e.target as Node)) setOpen(false);
    };
    window.addEventListener('pointerdown', onDown);
    return () => window.removeEventListener('pointerdown', onDown);
  }, []);

  // The ring on the picked spot.
  useEffect(() => {
    ringRef.current?.remove();
    ringRef.current = null;
    if (!picked || !map || !maplibre) return;
    const el = document.createElement('div');
    el.className = 'zmk-search-ring';
    el.title = picked.n;
    ringRef.current = new maplibre.Marker({ element: el }).setLngLat([picked.lng, picked.lat]).addTo(map);
    return () => { ringRef.current?.remove(); ringRef.current = null; };
  }, [picked, map, maplibre]);

  function go(p: Place) {
    setPicked(p);
    setQuery(p.n);
    setOpen(false);
    if (!map) return;
    const fly = () => {
      // Cancel whatever the camera is doing first — a flight that starts
      // while another animation is still running can be swallowed by it.
      map.stop();
      map.flyTo({ center: [p.lng, p.lat], zoom: p.k === 'place' && (p.c === 'town' || p.c === 'city') ? 14.5 : 17, duration: 900 });
    };
    if (map.loaded()) fly(); else map.once('idle', fly);
  }

  function clear() {
    setQuery('');
    setPicked(null);
    setOpen(false);
  }

  return (
    <div data-demo="map:search" className={cn('w-[min(320px,calc(100%-5rem))]', className)} ref={boxRef}>
      <style>{`
        .zmk-search-ring { width: 22px; height: 22px; border-radius: 9999px; border: 3px solid var(--color-brand);
          background: color-mix(in srgb, var(--color-brand) 25%, transparent); box-shadow: 0 0 0 0 color-mix(in srgb, var(--color-brand) 60%, transparent);
          animation: zmk-ring 1.6s ease-out infinite; }
        @keyframes zmk-ring { 0% { box-shadow: 0 0 0 0 color-mix(in srgb, var(--color-brand) 55%, transparent); } 100% { box-shadow: 0 0 0 18px transparent; } }
        @media (prefers-reduced-motion: reduce) { .zmk-search-ring { animation: none; } }
      `}</style>
      <div className="relative">
        <Search aria-hidden="true" className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />
        <input
          aria-autocomplete="list"
          aria-controls="map-search-results"
          aria-expanded={open && results.length > 0}
          aria-label="Search a place or landmark"
          className="h-10 w-full rounded-xl border border-[var(--color-surface-border)] bg-[var(--color-surface-card)] pl-9 pr-9 text-[13.5px] text-foreground shadow-[var(--shadow-md)] focus:border-[var(--color-brand)] focus:outline-none"
          onChange={e => { setQuery(e.target.value); setOpen(true); }}
          onFocus={() => { ensureLoaded(); setOpen(true); }}
          onKeyDown={e => {
            if (e.key === 'ArrowDown') { e.preventDefault(); setActive(a => Math.min(a + 1, results.length - 1)); }
            else if (e.key === 'ArrowUp') { e.preventDefault(); setActive(a => Math.max(a - 1, 0)); }
            else if (e.key === 'Enter' && results[active]) { e.preventDefault(); go(results[active]); }
            else if (e.key === 'Escape') { setOpen(false); }
          }}
          placeholder="Search a place or landmark…"
          role="combobox"
          type="text"
          value={query}
        />
        {query && (
          <button
            aria-label="Clear search"
            className="absolute right-2 top-1/2 flex size-6 -translate-y-1/2 items-center justify-center rounded-md text-muted-foreground hover:bg-[var(--color-surface-hover)] hover:text-foreground"
            onClick={clear}
            type="button"
          >
            <X aria-hidden="true" className="size-3.5" />
          </button>
        )}
      </div>

      {open && query.trim() && (
        <ul
          className="mt-1.5 max-h-80 overflow-y-auto rounded-xl border border-[var(--color-surface-border)] bg-[var(--color-surface-card)] py-1 shadow-[var(--shadow-lg)]"
          id="map-search-results"
          role="listbox"
        >
          {places === null ? (
            <li className="px-3 py-2 text-[12.5px] text-muted-foreground">Loading places…</li>
          ) : results.length === 0 ? (
            <li className="px-3 py-2 text-[12.5px] text-muted-foreground">No place in Biliran matches “{query.trim()}”.</li>
          ) : (
            results.map((p, i) => {
              const Icon = KIND_ICON[p.c] ?? MapPin;
              return (
                <li aria-selected={i === active} key={`${p.n}|${p.c}|${p.lat}`} role="option">
                  <button
                    className={cn('flex w-full items-center gap-2.5 px-3 py-2 text-left', i === active ? 'bg-[var(--color-surface-hover)]' : 'hover:bg-[var(--color-surface-hover)]')}
                    onClick={() => go(p)}
                    onMouseEnter={() => setActive(i)}
                    type="button"
                  >
                    <Icon aria-hidden="true" className="size-4 shrink-0 text-muted-foreground" />
                    <span className="min-w-0 flex-1">
                      <span className="block truncate text-[13px] font-semibold text-foreground">{p.n}</span>
                      <span className="block text-[11.5px] text-muted-foreground">{KIND_LABEL[p.c] ?? (p.k === 'place' ? 'Place' : 'Landmark')}</span>
                    </span>
                  </button>
                </li>
              );
            })
          )}
        </ul>
      )}
    </div>
  );
}
